name: labels-update

on:
  #schedule:
  #  - cron: '0 11,19 * * *'  # At 11:00 and 19:00 UTC every day
  workflow_dispatch:
    inputs:
      organization:
        description: 'Organization name to sync labels for'
        required: true
        default: 'bazingas-lab'

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML

      - name: Get organization repositories
        id: get_repos
        run: |
          python scripts/repos_list.py
          echo "✅ Repositórios obtidos com sucesso"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_CLH }}

      - name: Sync Labels for all repositories
        run: |
          python scripts/labels_sync.py
          echo "✅ Labels sincronizadas com sucesso"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_CLH }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update repository list and sync labels [skip ci]"
          git push
