name: labels-update

on:
  #schedule:
  #  - cron: '0 11,19 * * *'  # At 11:00 and 19:00 UTC every day
  workflow_dispatch:
    inputs:
      organization:
        description: 'Organization name to sync labels for'
        required: true
        default: 'bazingas-lab'

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_ORG: ${{ github.event.inputs.organization }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get organization repositories
        id: get_repos
        run: |
          python scripts/repos_list.py
          echo "✅ Repositórios obtidos com sucesso"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Sync Labels for all repositories
        run: |
          python scripts/labels_sync.py
          echo "✅ Labels sincronizadas com sucesso"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update repository list and sync labels [skip ci]"
            git push
          fi
